# Generated by Django 4.1.4 on 2022-12-11 04:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('prepaid', 'Prepaid'), ('postpaid', 'Pospaid')], default='prepaid', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('validity', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=20)),
                ('sms', models.CharField(max_length=20)),
                ('other_benifits', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(10)])),
                ('type', models.CharField(choices=[('prepaid', 'Prepaid'), ('postpaid', 'Pospaid')], default='prepaid', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.plans')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.serviceprovider')),
            ],
        ),
        migrations.AddField(
            model_name='plans',
            name='providers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.serviceprovider'),
        ),
        migrations.AddField(
            model_name='plans',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.zone'),
        ),
    ]
