# Generated by Django 4.1.4 on 2022-12-11 07:12

from django.db import migrations, models
import operators.models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_recharge_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='mobile_number',
            field=models.PositiveIntegerField(validators=[operators.models.number_validate]),
        ),
    ]
